"""empty message

Revision ID: 783bd9a67386
Revises: a22f81e1055e
Create Date: 2020-09-22 12:31:35.213980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783bd9a67386'
down_revision = 'a22f81e1055e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
